version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      #- "8200-9000:8200-9000"
    volumes:
      - ./www/:/var/www/:rw
      - ./conf_use/nginx/vhost:/etc/nginx/vhost/:rw
      - ./conf_use/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf_use/nginx/phalcon-admin.conf:/etc/nginx/phalcon-admin.conf:ro
      - ./conf_use/nginx/phalcon.conf:/etc/nginx/phalcon.conf:ro
      - ./conf_use/nginx/phalcon-rewrite.conf:/etc/nginx/phalcon-rewrite.conf:ro
      - ./conf_use/nginx/phalcon-admin-rewrite.conf:/etc/nginx/phalcon-admin-rewrite.conf:ro
      - ./conf_use/nginx/php-fpm.conf:/etc/nginx/php-fpm.conf:ro
      - ./conf_use/hosts:/etc/hosts:rw
      - ./log/:/var/log/lnmp/:rw
      # - ./conf_use/localtime:/etc/localtime:rw
    restart: always
    networks:
      - net-php56
      - net-php72

  #php56:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-php
  #     args:
  #       PHP_VERSION: 5.6
  #       SOURCE_LIST: jessie
  #       XDEBUG_VERSION: 2.5.5
  #       SWOOLE_VERSION: 2.0.11
  #       PAHCLON_VERSION: 3.4.0
  #       REDIS_VERSION: 4.1.1
  #       SUPPORT_MCRYPT: "true"
  #       BUILT_IN_OPCACHE: "true"
  #   expose:
  #     - "9000"
  #   volumes:
  #    - ./www/:/var/www/:rw
  #    - ./conf_use/php/php-56.ini:/usr/local/etc/php/php.ini:ro
  #    - ./conf_use/php/php-fpm-56.conf:/usr/local/etc/php-fpm.d/www.conf:rw
  #    - ./conf_use/hosts:/etc/hosts:rw
  #    - ./log/:/var/log/lnmp/:rw
  #    - ./conf_use/localtime:/etc/localtime:rw
  #   restart: always
  #   cap_add:
  #     - SYS_PTRACE
  #   networks:
  #     - net-php56
  #     - net-mysql
  #     - net-redis

  php72:
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        PHP_VERSION: 7.2
        SOURCE_LIST: stretch
        XDEBUG_VERSION: 2.6.1
        SWOOLE_VERSION: 4.2.1
        PAHCLON_VERSION: 3.4.0
        REDIS_VERSION: 4.1.1
        SUPPORT_MCRYPT: "false"
        BUILT_IN_OPCACHE: "true"
    expose:
      - "9000"
    volumes:
     - ./www/:/var/www/:rw
     - ./conf_use/php/php-72.ini:/usr/local/etc/php/php.ini:ro
     - ./conf_use/php/php-fpm-72.conf:/usr/local/etc/php-fpm.d/www.conf:rw
     - ./conf_use/hosts:/etc/hosts:rw
     - ./log/:/var/log/lnmp/:rw
     - ./conf_use/localtime:/etc/localtime:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php72
      - net-mysql
      - net-redis

  mysql8:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf_use/mysql.conf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql/data:/var/lib/mysql:rw
      #- ./data/mysql/mysql_sock:/var/run/mysqld
      - ./conf_use/localtime:/etc/localtime:rw
    #restart: always
    command:
      --default-authentication-plugin=mysql_native_password #这行代码解决无法访问的问题
      #--character-set-server=utf8mb4
      #--collation-server=utf8mb4_general_ci
      #--explicit_defaults_for_timestamp=true
      #--lower_case_table_names=1
      #--max_allowed_packet=128M;
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  redis:
    image: redis:4.0
    restart: always
    volumes:
      - ./data/redis:/data
      - ./conf_use/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./conf_use/localtime:/etc/localtime:rw
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - net-redis
    ports:
      - "6379:6379"

  portainer:
    image: portainer/portainer:latest
    ports:
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:cached
      - ./data/portainer/:/data:cached
      - ./conf_use/localtime:/etc/localtime:rw

networks:
  net-php72:
  net-php56:
  net-mysql:
  net-redis:
